### ISSUE TITLE
Add DowloadLink to Dataset Templates if provided

### ISSUE THREAD

**Issue by chrisgorgo** [openschemas/schemaorg#21]
The landing pages generated by this extractor (example): https://vsoch.github.io/zenodo-ml/) are great for web crawlers, but not so much for humans. A visitor unfamiliar with schema.org might not understand what such page means when redirected from search results. Rendering: title, description and clear instructions on how to download the datasets would greatly improve the readability of the landing page.

Thanks for putting this project together!

**Comment by vsoch** [comment]
@chrisgorgo which of these attributes does Google require for Datasets? https://schema.org/DataDownload

**Comment by vsoch** [comment]
Also note that schemaorg 3.5 (stable) was released just a day ago!

**Comment by chrisgorgo** [comment]
The only two required properties are `name` and `description` (see https://developers.google.com/search/docs/data-types/dataset#dataset).

**Comment by vsoch** [comment]
ah ok, and that's for the dataset. So a Dataset does not even require a DownloadData attribute, let alone some subset of attributes that belong to it. Do you have a suggested set (for DataDownload, not Dataset)?

**Comment by vsoch** [comment]
I'm asking here - https://github.com/schemaorg/schemaorg/issues/2198
