### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by nsheff** [openschemas/schemaorg#23]
Link to `parse_dataset.py` is dead on https://github.com/openschemas/schemaorg/tree/master/examples/google

**Comment by vsoch** [comment]
I'll fix that up - the general "parse_*" files were replaced with the "extract_*" files, and I went further to create [extractors](https://github.com/openschemas/extractors) for different content types that would generate into different templates (for GitHub pages, etc.) The only one that is really useful given how the metadata is used is Google Datasets, which go into Dataset search. I asked some of the schema.org team about how easy/hard it would be to have search for other content types (e.g., containers) and the answer was hard, build something first and show it's useful.

**Comment by vsoch** [comment]
All fixed. I don't normally just push to master, but I'm being a bit lazy since it's just documentation stuffs. Thanks for the catch!
