### ISSUE TITLE
Can not find how to retrieve schema ?

### ISSUE THREAD

**Issue by redradist** [openschemas/schemaorg#33]
Can not find how to retrieve schema for example for https://schema.org/SportsEvent to verify data structure ?

I have tried to find examples in `Python` or `JavaScript`, but have not found ... (

Any help will be appreciated ...

**Comment by vsoch** [comment]
Did you not see the documentation? https://openschemas.github.io/schemaorg/

**Comment by redradist** [comment]
> 
> 
> Did you not see the documentation? https://openschemas.github.io/schemaorg/

@vsoch 
Yeah, but I have not found example with getting schema and verifying it

I have found this example, but cannot figure out how to get specification for https://schema.org/SportsEvent from schema.org ... ?

**Comment by vsoch** [comment]
Do you want to give me the schema you want to verify and I can try to help?

**Comment by redradist** [comment]
> 
> 
> Do you want to give me the schema you want to verify and I can try to help?

@vsoch I just want to understand how to get this schema https://schema.org/SportsEvent and to apply it to schema.org versifier ...

I do not have any particular data at this moment ...

**Comment by vsoch** [comment]
okay let me take a look and see if I can put together a dummy example. Give me a few minutes!

**Comment by vsoch** [comment]
here you go! https://github.com/openschemas/schemaorg/tree/master/examples/sports-event

That walks through how you could put together a recipe for validation, and then define a schema, and validate it for a SportsEvent.

**Comment by redradist** [comment]
> 
> 
> here you go! https://github.com/openschemas/schemaorg/tree/master/examples/sports-event
> 
> That walks through how you could put together a recipe for validation, and then define a schema, and validate it for a SportsEvent.

@vsoch Thanks a lot !!
But as I understood I have manually to specify needed fields ... is there a way to require to check all fields on availability ?

**Comment by vsoch** [comment]
if you look at the data exports, unlike the site, there isn't any representation of what is required vs. not. I suspect because this will vary based on the user case. If you are able to find somewhere in the data that says something about what is required, I'd be happy to add this functionality to the library (I could not find anything). If you _really_ want to require all fields (this would be a lot) then you could probably just export the whole thing to yaml, but you'd quickly hit a potential issue that when you discover a subclass you also require all it's properties, and that could blow up. I'm giving it a shot now, I'll let you know if that happens :)

**Comment by redradist** [comment]
> 
> 
> if you look at the data exports, unlike the site, there isn't any representation of what is required vs. not. I suspect because this will vary based on the user case. If you are able to find somewhere in the data that says something about what is required, I'd be happy to add this functionality to the library (I could not find anything). If you _really_ want to require all fields (this would be a lot) then you could probably just export the whole thing to yaml, but you'd quickly hit a potential issue that when you discover a subclass you also require all it's properties, and that could blow up. I'm giving it a shot now, I'll let you know if that happens :)

@vsoch
Do you mean that I cannot parse from JSON string object according the schema ?

**Comment by vsoch** [comment]
You could, but it's not going to be very helpful. https://github.com/openschemas/schemaorg/tree/master/examples/require-all. It's a graph with many different types connected, so it's not a simple matter of just dumping one type. When you require one type, you also have to require those subtypes and their properties, and that expands infinitum. I think you should perhaps think carefully about what you are trying to accomplish, define your required properties (including other classes and required properties for each) and go from there.

**Comment by vsoch** [comment]
So - if you just want to validate that _everything is there_ but not necessarily that the everything is correct, you could do the first step in that example. Beyond that, I'd recommend really looking at your use case and deciding what sub types are included, and the properties for each. For example, for the SportsEvent there can be an awayTeam and homeTeam, and each of those can be a Person OR a SportsTeam. I would suspect you would want one or the other - and this isn't something that can be automatically known. The example I provided would parse and add both types to the list.
